
  - label: run bats tests
    plugins:
      - docker-compose#v3.9.0:
          run: tests
  - label: ":sparkles: lint"
    plugins:
      - plugin-linter#v3.0.0:
          id: robertkruk/spell-checker
  - label: "spell check md files"
    plugins:
      - robertkruk/spell-checker#v0.1.5:
          pattern: '*.md'