
  - label: ":sparkles: lint"
    plugins:
      - plugin-linter#v1.0.0:
          id: robertkruk/spell-checker
  - label: "spell check md files"
    plugins:
      - robertkruk/spellchecker#v0.1:
          pattern: '*.md'